apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nyu3szkz1-dotnet-basic
  janus-idp.io/tekton: nyu3szkz1-dotnet-basic
  backstage.io/kubernetes-id: nyu3szkz1-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nyu3szkz1-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
